# Generated by Django 3.1.5 on 2021-02-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_accomodation_accomodation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='link',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='general_review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='img_link_2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='img_link_3',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='img_link_4',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='img_link_5',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='min_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='total_review_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
