# Generated by Django 3.1.5 on 2021-02-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210209_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
