# Generated by Django 3.1.5 on 2021-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_accomodation_owner_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='owner_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
