# Generated by Django 3.1.5 on 2021-02-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_accomodation_owner_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='owner_comment',
        ),
    ]
