# Generated by Django 3.1.5 on 2021-02-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='accomodation_type',
            field=models.TextField(null=True),
        ),
    ]
