# Generated by Django 3.1.5 on 2021-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_accomodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='longitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='roomID',
            field=models.TextField(),
        ),
    ]
