# Generated by Django 3.1.5 on 2021-02-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210205_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='rome_name',
            new_name='room_name',
        ),
    ]
