# Generated by Django 3.1.5 on 2021-02-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_accomodation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='owner_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='accomodation_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='general_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='img_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='img_link_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='img_link_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='img_link_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='total_review_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
