# Generated by Django 3.1.5 on 2021-02-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210209_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='owner_comment',
        ),
    ]
